name: CI-docker

on:
    push:
    pull_request:
jobs:
    docker-build:
        runs-on: ubuntu-20.04
        steps:
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: docker-run
            run: docker run -dt --name test debian:testing;
        -
            name: apt-get update
            run: docker exec test apt-get update;
        -
            name: install dependencies
            run: |
                docker exec test apt-get install -V                     \
                        build-essential                                 \
                        libbsd-dev                                      \
                        libcurl4-openssl-dev                            \
                        libgmp3-dev                                     \
                        libgsl-dev                                      \
                        libncurses-dev                                  \
                        libopencv-dev                                   \
                        libtesseract-dev                                \
                        libzbar-dev                                     \
                        pkg-config                                      \
                        --yes;
        -
            name: cp repo
            run: docker cp ./ test:/usr/local/src/libalx/;
        -
            name: build
            run: docker exec test make -C /usr/local/src/libalx/;
        -
            name: install
            run: docker exec test make install -C /usr/local/src/libalx/;
