name: CI-docker

on:
    push:
    pull_request:
jobs:
    docker-build:
        runs-on: ubuntu-20.04
        steps:
        -
            name: checkout
            uses: actions/checkout@v2
        -
            name: docker-build
            run: docker build -t 'alejandrocolomar/libalx:ci' .;
